/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.apache.commons.io.FileUtils;
/**
 *
 * @author stakesk
 */
public class Diagnostika extends javax.swing.JFrame {

    /**
     * Creates new form Diagnostika
     */
    public long memBefore;
    
    public Diagnostika() {
        memBefore = Runtime.getRuntime().totalMemory();
        initComponents();
        setAll();
    }
    
    private void setAll(){
        
        OSName.setText(System.getProperty("os.name"));
        OSVersion.setText(System.getProperty("os.version"));
        OSArchitecture.setText(System.getProperty("os.arch"));
        UserName.setText(System.getProperty("user.name"));
        javaVersion.setText(System.getProperty("java.version"));
        Path path = Paths.get(System.getProperty("user.dir"));
        fileName.setText(path.getFileName().toString());
        
        fileSize.setText(String.valueOf(FileUtils.sizeOfDirectory(new File(System.getProperty("user.dir")))/1024));
        jvmAllAvailableMemory.setText(String.valueOf(Runtime.getRuntime().maxMemory()/1024));
        jvmAvailableMemory.setText(String.valueOf(Runtime.getRuntime().freeMemory()/1024));
        freeMemoryBefAll.setText(String.valueOf(memBefore/1024));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        OSName = new javax.swing.JTextField();
        OSVersion = new javax.swing.JTextField();
        OSArchitecture = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        javaVersion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fileName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fileSize = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jvmAllAvailableMemory = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jvmAvailableMemory = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        freeMemoryBefAll = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Diagnostika");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 140, 40));

        jLabel2.setText("OS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Meno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Verzia:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel5.setText("Architektura:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));
        jPanel1.add(OSName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 100, -1));
        jPanel1.add(OSVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 160, -1));
        jPanel1.add(OSArchitecture, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 110, -1));

        jLabel6.setText("Meno používateľa: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 160, -1));

        jLabel7.setText("Verzia JAVY:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel1.add(javaVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 160, -1));

        jLabel8.setText("Názov použ/pracovného priečinku:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        jPanel1.add(fileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 370, -1));

        jLabel9.setText("Veľkosť p/p priečinku:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        jPanel1.add(fileSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 160, -1));

        jLabel10.setText("Celková dostupná pamäť pre JVM:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
        jPanel1.add(jvmAllAvailableMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 160, -1));

        jLabel11.setText("Dostupná pamäť pre JVM:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));
        jPanel1.add(jvmAvailableMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 160, -1));

        jLabel12.setText("Voľná pamäť pred alokáciou:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));
        jPanel1.add(freeMemoryBefAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 160, -1));

        jLabel13.setText("KB");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        jLabel14.setText("KB");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        jLabel15.setText("KB");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel16.setText("KB");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnostika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnostika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnostika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnostika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnostika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OSArchitecture;
    private javax.swing.JTextField OSName;
    private javax.swing.JTextField OSVersion;
    private javax.swing.JTextField UserName;
    private javax.swing.JTextField fileName;
    private javax.swing.JTextField fileSize;
    private javax.swing.JTextField freeMemoryBefAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField javaVersion;
    private javax.swing.JTextField jvmAllAvailableMemory;
    private javax.swing.JTextField jvmAvailableMemory;
    // End of variables declaration//GEN-END:variables
}
