/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit;

import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author xluleym
 */
public class Checker extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Checker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        allPanels = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        pnlChecker = new javax.swing.JPanel();
        txtRegex = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtString = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        txtDecision = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allPanels.setLayout(new java.awt.CardLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Vitajte");
        pnlMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        btnContinue.setText("Pokračovať");
        btnContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnContinueMouseReleased(evt);
            }
        });
        pnlMenu.add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        allPanels.add(pnlMenu, "card3");

        pnlChecker.setBackground(new java.awt.Color(255, 255, 255));
        pnlChecker.setForeground(new java.awt.Color(255, 255, 255));
        pnlChecker.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlChecker.add(txtRegex, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 220, -1));

        txtString.setColumns(20);
        txtString.setRows(5);
        jScrollPane1.setViewportView(txtString);

        pnlChecker.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Checker");
        pnlChecker.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Reťazec na overenie");
        pnlChecker.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Regulárny výraz");
        pnlChecker.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        btnConfirm.setText("Overiť");
        btnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnConfirmMouseReleased(evt);
            }
        });
        pnlChecker.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));
        pnlChecker.add(txtDecision, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 60, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("male");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseReleased(evt);
            }
        });
        pnlChecker.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("velke");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseReleased(evt);
            }
        });
        pnlChecker.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        btnClean.setText("zmazanie neviditelných a netlačitelných znakov");
        btnClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCleanMouseReleased(evt);
            }
        });
        pnlChecker.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 310, -1));

        allPanels.add(pnlChecker, "cardChecker");

        getContentPane().add(allPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 511, 409));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseReleased
        
        String regex = txtRegex.getText();
        String stringToCheck = txtString.getText();
        
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(stringToCheck);
        if (matcher.matches()){
            txtDecision.setText("OK");
        }else{
            txtDecision.setText("NG");
        }
        
        
        
    }//GEN-LAST:event_btnConfirmMouseReleased

    private void btnContinueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseReleased
        CardLayout card = (CardLayout)allPanels.getLayout();
        card.show(allPanels, "cardChecker");
    }//GEN-LAST:event_btnContinueMouseReleased

    private void jRadioButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseReleased
        String str = txtString.getText();
        txtString.setText(str.toLowerCase());
    }//GEN-LAST:event_jRadioButton1MouseReleased

    private void jRadioButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseReleased
        String str = txtString.getText();
        
        txtString.setText(str.toUpperCase());
    }//GEN-LAST:event_jRadioButton2MouseReleased

    private void btnCleanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanMouseReleased
        String str = txtString.getText();
        
        txtString.setText(str.trim().replaceAll("\\p{C}", ""));
    }//GEN-LAST:event_btnCleanMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allPanels;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnContinue;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlChecker;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JTextField txtDecision;
    private javax.swing.JTextField txtRegex;
    private javax.swing.JTextArea txtString;
    // End of variables declaration//GEN-END:variables
}
